services:
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Asde71.4Asde71.4"
    build: sql
    container_name: mssql2017
    hostname: mssql
    volumes:
      - ./sql:/sql
      - ./dbData/data:/var/opt/mssql/data 
      - ./dbData/log:/var/opt/mssql/log
      - ./dbData/secrets:/var/opt/mssql/secrets
    ports:
      - "1433:1433"
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Asde71.4 -Q 'SELECT 1' || exit 1"
        ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
#docker compose down;docker compose build;docker compose up -d